version: "3.8"

services:
  memos:
    container_name: notes
    build: .
    ports:
      - "5230:5230"
    volumes:
      - ./data:/var/opt/memos
    env_file:
      - .env
    restart: unless-stopped
